### ISSUE TITLE
Touchscreen issues #1: Search radically slows down UI

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#7] opened 2017-09-30 09:03 UTC
Typing a general search such as "dodo" radically slows down the whole UI on James' touchscreen. We should check indexes are properly set on the DB, but I don't think this is the root of the problems as there are problems even when the server is running on another computer. It may be to do with returning too many results into the search box (possibly linked to https://github.com/OneZoom/OZtree/issues/6)

**Comment by jrosindell** [comment] 2017-10-07 20:56
This issue seems less prominent now for some reason - at least that was so on the latest tests I've been running

**Comment by hyanwong** [comment] 2017-10-11 13:41
I have implemented some console logging to help debug this. Can you try searching for something on the touchscreen and see what is logged in the js console?

**Comment by hyanwong** [comment] 2017-10-12 09:04
We get SQL errors like this:

```
/Library/Python/2.7/site-packages/pymysql/cursors.py:161: Warning: Memory capacity of 8388608 bytes for 'range_optimizer_max_mem_size' exceeded. Range optimization was not done for this query.
```

**Comment by jrosindell** [comment] 2018-01-17 18:34
OK I've just seen that the UI will fire off calls to search for just single letters, without enter being pressed or anything like that.  I thought we planned to stop this right?  The server does not give any return for single letter searches.

**Comment by jrosindell** [comment] 2018-01-17 18:34
I suggest that we restrict searches back to three letters or two letter ONLY if the user presses enter and one letter never.

**Comment by jrosindell** [comment] 2018-01-17 18:35
Also, we should comment out the console logs (or remove them altogether) before closing this issue and after we're happy the problem is solved.

**Comment by jrosindell** [comment] 2018-04-10 23:01
This is now fixed with latest push.

**Closed by jrosindell** 2018-04-10 23:01 UTC
