### ISSUE TITLE
email people to thank them after renewal of sponsorships

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#592] opened 2022-07-14 13:25 UTC
The auto e-mail system does not thank people for renewals - it should do.

**Comment by jrosindell** [comment] 2022-10-31 00:54
I think this needs another simple template to say thank you for renewing and then providing again a link to the renewals page rather than trying to code anything specific into the e-mail itself beyond the name of the person.  This e-mail should be triggered when the PayPal post is processed successfully and thus the renewal has been done.

**Comment by lentinj** [comment] 2022-11-11 11:00
How does this relate to #555? It must have thanked them if the wording is wrong :)

I'll close that one and consider this one the same thought as I had in there, i.e. we should have a more intelligent sponsor_thanks page with some links.

**Comment by lentinj** [comment] 2022-11-11 16:40
This is trickier than it seems, since we verify details as part of the PayPal confirmation response. Slow responses to this, because you're doing things like sending thank-you e-mails, are explicitly discouraged by PayPal. Obviously we can ignore PayPal, do it anyway and see if we get away with it.

We could do something like clear ``emailed_re_sponsorship`` for anything where we copy the verified details from a previous row in ``reservation_confirm_payment()``, and then modify ``send_sponsorship_emails.py`` to notice this and send the thankyou e-mails for us. However, ``send_sponsorship_emails`` has no inherent timing for the reminders, it just relies on being run once a week. Adding yet another cron job wouldn't impress @hyanwong either I'm guessing.

It also depends on what the mail setup on the actual OneZoom server is. If it's configured to send e-mail to exim/postfix running on localhost then it's probably not worth worrying about. Anything we construct to solve this will be some kind of queuing system with another process taking jobs off the queue to send the e-mails. That's exactly what the local mail daemon is for anyway. @hyanwong is this the case?

**Comment by lentinj** [comment] 2023-03-31 21:07
This is a duplicate of https://github.com/OneZoom/OZtree/issues/452 I think

**Closed by lentinj** 2023-03-31 21:07 UTC
Labels: Renewals portal
