### ISSUE TITLE
Problems in V3.6 with sponsorship form submission

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#471] opened 2022-01-23 11:59 UTC
Here’s what I’ve been doing and I’ve repeated it three times with the same result…..

click (in Safari) on for everyone - your name on the tree
select a species
enter ‘test’ in as the name to appear on the leaf - change nothing else on the form.
press accept terms and donate
log in via sandbox and make successful payment
return to OneZoom - all apparently OK

not only does PayPal not post but the ‘test’ has also not be recorded in the database.

**Comment by hyanwong** [comment] 2022-01-23 16:42
The problem seems to be that this call in `pp_process_post`: https://github.com/OneZoom/OZtree/blob/7977faee00a70ff0b7171535ed52c86700287adb/controllers/default.py#L1444

is returning a 503 from PayPal. Sometimes it's saying "HTTP Error 503: first byte timeout", other times nothing.

**Comment by hyanwong** [comment] 2022-01-23 16:48
Here's an example log file:

```
{"quantity": "1", "first_name": "John", "item_number": "leaf sponsorship - Ochotona princeps", "payment_date": "07:58:33 Jan 23, 2022 PST", "receiver_email": "mail@onezoom.org", "business": "mail@onezoom.org", "txn_type": "web_accept", "verify_sign": "A-VMloqqF3r-NNxBa97qCDH9GGd4AlfdVn-beWPMoeE0vhQetcun60mh", "discount": "0.00", "mc_gross": "150.00", "payer_email": "sb-y7jhw1408213@personal.example.com", "payment_status": "Completed", "transaction_subject": "", "last_name": "Doe", "test_ipn": "1", "receiver_id": "3K2RSXB98PJCC", "protection_eligibility": "Ineligible", "txn_id": "32M12025VH7211255", "payment_type": "instant", "shipping_discount": "0.00", "mc_currency": "GBP", "payer_status": "verified", "item_name": "Donation to OneZoom (Ochotona princeps)", "residence_country": "GB", "charset": "windows-1252", "insurance_amount": "0.00", "custom": "", "ipn_track_id": "2cab34180f8df", "payer_id": "VYL6BV9ZQBS7G", "payment_gross": "", "mc_fee": "5.30", "shipping_method": "Default", "notify_version": "3.9", "payment_fee": "", "__oz_error": "HTTP Error 503: Service Unavailable", "__oz_traceback": ["Traceback (most recent call last):\n", "  File \"/home/web2py/OneZoomComplete_DEV/applications/OZtree/controllers/default.py\", line 1447, in pp_process_post\n    'content-type': 'application/x-www-form-urlencoded',\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 569, in error\n    return self._call_chain(*args)\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n", "  File \"/usr/local/lib/python3.7/urllib/request.py\", line 649, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n", "urllib.error.HTTPError: HTTP Error 503: Service Unavailable\n"]}
```

**Comment by hyanwong** [comment] 2022-01-23 17:02
But actually it's working now. I'm inclined to put this down to a PayPal problem, but we should make sure that it doesn't scupper us if it happens again? So do we need to wrap the `urllib.request.urlopen` call back to PayPal in a `try: except` black, and if we can't get through, still activate the sponsorship but somehow flag that this hasn't been confirmed by paypal?

**Comment by hyanwong** [comment] 2022-01-24 08:39
From slack, where I said:
>I think we simply want to implement something so that even if there is a 503 from PayPal, we update the reservations table so that the sponsorship is listed in manage/SPONSOR_VALIDATE but flag up somehow they there is a problem reverifying the PP payment, so the sponsorship might need to be manually checked

**Comment by jrosindell** [comment] 2022-01-24 09:24
I think this is likely just that I hadn't realised Beta database was migrated to a new address with the old stale database left turned on - probably my initial issue is a non issue

**Comment by hyanwong** [comment] 2022-01-24 09:38
> I think this is likely just that I hadn't realised Beta database was migrated to a new address with the old stale database left turned on - probably my initial issue is a non issue

You probably were looking at the wrong DB, but from my reading of the code, we don't touch the DB on pp_process_post until out re-post back to PayPal succeeds, and it was failing (for PP reasons) in some cases before.

**Comment by lentinj** [comment] 2022-01-24 10:58
To summarise our conversation:

The core issue was PayPal's sandbox callback facility being off. Hopefully this isn't a recurring problem, and in theory will happen a lot less in production than the sandbox. Also it shouldn't be a situation we need to worry about (in theory) since that's why PayPal retry the IPN callbacks.

But it'd be nice to have more visibility of people that are having PayPal problems. We could log the details we got regardless of whether PayPal says they're kosher but this makes me nervous. Regardless it won't catch things like #468 where the failure is happening before they managed to pay with PayPal.

What we could do is make sure that people that get to the point of trying to sponsor appear in SPONSOR_VALIDATE, and add the ability to clear the reservation eventually (possibly after e-mailing to check what happened).

**Comment by hyanwong** [comment] 2022-01-24 22:10
Closing this and moving the remaining queries to a new issue: https://github.com/OneZoom/OZtree/issues/481

**Closed by hyanwong** 2022-01-24 22:10 UTC
