### ISSUE TITLE
Sponsor renewal does not port all information to the new sponsorship row

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#557] opened 2022-05-20 19:47 UTC
@jrosindell and I have just tried renewing a species on the production server, and there appears to be a serious bug. The original row is transferred OK to the `expired_reservations` table, but the details remaining in the original `reservations` table are bad. Here are the first few fields, which are OK. 
<img width="1066" alt="Screenshot 2022-05-20 at 20 33 05" src="https://user-images.githubusercontent.com/4699014/169598994-7ce74b73-5a46-4972-ae8e-8cdcca276782.png">

And the `user_sponsor_name` has transferred OK. But all the other fields, such as `username`, `e_mail`, `user_sponsor_kind`, `user_giftaid`, and all the `verified_XXX` fields are empty. This might be because a new row has been created for the entry (and the old one deleted), as evidenced by the fact that the ID in the snapshot above is a high number (almost the last row added to the reservations table, at the moment). I suspect (but am not sure) that we intended to copy the row to `expired_reservations` and then update it, rather than delete the existing row it and create new one. Is that right @lentinj.

**Comment by jrosindell** [comment] 2022-05-20 19:56
@lentinj - while you're on this I wonder if you could also please add to the sponsor_renew_reminder e-mail text an additional reference to that user's personal sponsorship page - currently that's referenced from the renewal html page only.  I think it's nice for the user to see this from the e-mail as well.

**Comment by jrosindell** [comment] 2022-05-20 20:47
I'm about to push some updates to improve the e-mail template but please do check the controller serves the correct things to make it work - thanks @lentinj

**Comment by lentinj** [comment] 2022-05-22 09:54
@hyanwong This sounds familiar, I suspect a patch has fallen down the back of a sofa. Will have a look tomorrow and let you know.

**Comment by lentinj** [comment] 2022-05-23 08:40
> This might be because a new row has been created for the entry (and the old one deleted), as evidenced by the fact that the ID in the snapshot above is a high number (almost the last row added to the reservations table, at the moment). I suspect (but am not sure) that we intended to copy the row to expired_reservations and then update it, rather than delete the existing row it and create new one. Is that right @lentinj.

No, this is expected. Renewing by expiring and repurchasing in a single transaction means we can share code with the expire then repurchase case.

I can't reproduce with the tests yet, will try doing something end-to-end. Just to check, this is ``3.7`` with https://github.com/OneZoom/OZtree/commit/0e0165c367a82de14da83502e98d86e16238ee4f ?

**Comment by jrosindell** [comment] 2022-05-23 09:22
@lentinj not it's not with 3.7 I think the server is still running 3.6

**Comment by jrosindell** [comment] 2022-10-31 00:58
I think this is now fixed based on the changes Yan and I made to the renewals system recently so I'm closing.  Having tested it just now with another renewal all seems to be fine.

**Closed by jrosindell** 2022-10-31 00:58 UTC
