### ISSUE TITLE
Embedding clips of YouTube videos

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#737] opened 2024-03-09 18:49 UTC
I'm not sure how easy this one will be but YouTube has the ability to set up an embed of a clip from a video.  I think this is very useful in tours as we need to produce something about 7 mins long but a lot of high quality YouTube videos are also 7 mins long in themselves.  Here's a clip I did of one that I think would work brilliantly but it breaks when I put this in as a media item

https://www.youtube.com/embed/2OitEHoPpTE?si=isqP7sGs8qEULP1l&amp;clip=UgkxPWw-MH32eX1nNy3LBd0y5m8AR9e3qMAA&amp;clipt=EL-gARie9QQ

**Comment by lentinj** [comment] 2024-03-12 16:41
There's 2 immediately obvious issues, the URL pasted above has "&" escaped as "&amp;", and we weren't joining our QS params together with any existing ones in the Youtube URL (fixed with the above).

Now adding ``"https://www.youtube.com/embed/2OitEHoPpTE?si=isqP7sGs8qEULP1l&clip=UgkxPWw-MH32eX1nNy3LBd0y5m8AR9e3qMAA&clipt=EL-gARie9QQ"`` to a tour will load the video, but the clip will be ignored.

If you open the URL OneZoom uses into a new browser, the clip is recognised and used.

I can't find much mention of the ``clip`` & ``clipt`` parameters in reference to iframes, it may be they're just not supported.

**Comment by lentinj** [comment] 2024-03-12 16:51
Another option would be adding ``?start=60&end=70``, [which are at least documented](https://developers.google.com/youtube/player_parameters), however, they seem to be similarly ignored.

Not immediately obvious what's going wrong at this point, or if Youtube just don't let you do this any more.

**Comment by davidebbo** [comment] 2024-03-12 17:41
If I create a trivial HTML page containing only the following (using @jrosindell's initial URL), it works fine and the clip is honored (in Chrome on Windows):

```
<iframe width="420" height="315"
    src="https://www.youtube.com/embed/2OitEHoPpTE?si=isqP7sGs8qEULP1l&amp;clip=UgkxPWw-MH32eX1nNy3LBd0y5m8AR9e3qMAA&amp;clipt=EL-gARie9QQ">
</iframe>
```

This leads me to think that the issue is more OneZoom than YouTube specific?

**Comment by lentinj** [comment] 2024-03-12 18:21
It also works when viewing the tour HTML source directly too actually.

The clip options vanish once the ``YT.Player()`` object is created - https://github.com/OneZoom/OZtree/blob/main/OZprivate/rawJS/OZTreeModule/src/tour/handler/Youtube.js#L43

Maybe we need to parse options out of the URL and put them into ``playerVars``? Or the assumption is you'd use ``seekTo()`` once the JS API is around.

**Comment by davidebbo** [comment] 2024-03-12 19:00
`playerVars` seems to work in a minimal test, e.g.

```javascript
        player = new YT.Player('player', {
            height: '315',
            width: '420',
            videoId: '2OitEHoPpTE',
            playerVars: {
                clip: 'UgkxPWw-MH32eX1nNy3LBd0y5m8AR9e3qMAA&amp',
                clipt: 'EL-gARie9QQ'
            }
```

**Comment by lentinj** [comment] 2024-03-13 10:40
> playerVars seems to work in a minimal test

We're attaching to an existing player with ``enablejsapi=1``, not creating a new one.

Destroying the iframe, parsing it's Youtube URL and recreating would be possible, but seems somewhat unnecessary and brittle.

**Comment by jrosindell** [comment] 2024-03-14 09:03
Thanks @davidebbo and @lentinj for these thoughts.  Honestly, I'm not sure where this leaves us though - my guess is that it leaves us in a place where it's disproportionately painful to solve this issue for now so maybe we'll need to park it.

**Comment by lentinj** [comment] 2024-03-15 11:22
Right, so the problem here is calling [player.stopVideo()](https://developers.google.com/youtube/iframe_api_reference). Doing so also clears the clip, so when we ``playVideo()`` we start at the very beginning.

This was made more confusing by the initial tourstop closed state causing a ``stopVideo()`` before we've even started. That's easy enough to fix though.

More annoying is the interaction with our prev/next buttons. The reason for calling ``stopVideo()`` was that the video then restarted from the beginning if they came back to the tourstop. We can use ``pauseVideo()``, but then pressing back restarts from the middle, which feels wrong.

What does work is recording the current position as soon as the player starts playing, and when we leave a tourstop ``pauseVideo()`` then ``seekTo(startPos)``. Having all previous videos paused rather than stopped feels a bit wasteful, but probably not the end of the world.

**Closed** 2024-03-15 12:02 UTC

**Comment by lentinj** [comment] 2024-03-15 12:07
@davidebbo any comments on https://github.com/OneZoom/OZtree/pull/761/commits/490bc7110cbe648e351d67dd2b7b1aa2ae0fbb3a in particular would be appreciated - it feels a bit naive, but reloading the video clip and all seems like a worse choice.

**Comment by davidebbo** [comment] 2024-03-15 13:10
@lentinj I'm missing a bit of context, as I have not seen what this UI looks like at all. I'm also far from an expert on the YT player.

Is a given YT player only used for one video, and never switched to a different one? I'm pretty sure that's the case, and if so, the logic looks reasonable. But if it's ever reused across videos, then `el.ozStartPos` would need to be reset to `undefined`.

**Comment by lentinj** [comment] 2024-03-15 15:55
> Is a given YT player only used for one video, and never switched to a different one?

Yeah, a tour might have lots of videos, but they all have their own player.

Thanks!

**Comment by davidebbo** [comment] 2024-03-15 17:03
> Yeah, a tour might have lots of videos, but they all have their own player.

How many videos are we talking about under a reasonable scenario? Is there a possible resource usage issue that might push memory requirements a bit higher than we'd want?

**Comment by lentinj** [comment] 2024-03-15 17:10
I'm not sure, but I definitely share your worries.

@jrosindell how many videos are likely in any one tour?

**Comment by lentinj** [comment] 2024-03-15 21:48
Actually, if we know the start position is ``0``, there's nothing stopping us using ``stopVideo()``.

Although the docs do say it's for "rare situations when you know that the user will not be watching additional video in the player". I'm guessing the average user won't use the back button as much as I do, but some replaying is certainly possible.
