### ISSUE TITLE
Homepage embedded tree

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#213] opened 2019-11-05 10:06 UTC
Use example from layout_minimal

**Comment by hyanwong** [comment] 2019-11-05 10:24
For reference, layout_minimal.html is in the branch at https://github.com/OneZoom/OZtree/tree/minimal-layout

**Comment by lentinj** [comment] 2019-11-11 18:14
@hyanwong The above makes the demo seem a lot closer to the design. Couple of points:

* Controls only appear once you get to the first location, is that intentional?
* The tour JS seems to be setting the control button content (I was hoping to bung in some SVG in the template), and in particular gets the forward and backward gets the wrong way round.

**Comment by hyanwong** [comment] 2019-11-11 21:32
> * Controls only appear once you get to the first location, is that intentional?

Ah, that's a good point. I had hoped that setting `"transition_in_visibility": "show_self"` in `homepage_animation.js` would show the first point immediately, but I guess it doesn't. That's probably a bug. I'll investigate.

> * The tour JS seems to be setting the control button content (I was hoping to bung in some SVG in the template), and in particular gets the forward and backward gets the wrong way round.

Oops - yes, I see. that's also in `homepage_animation.js`, and the `>` and `<` signs are the wrong way round. Since AFAIK we are only using the `homepage_animation_template.html` template for this homepage thing, you can just take out the "update_class" setting in "tourstop_shared", and hard-code any symbols or whatever directly into `homepage_animation_template.html`. The overriding thing was intended for more general tours, where we might want the tour to be able to use the same template but re-write the text on the buttons etc.

Does that make sense?

**Comment by lentinj** [comment] 2019-11-11 21:37
One other thing I forgot to mention, can we change "opacity:1 / 0" for each set of controls instead of "display: none"? Then they can fade in/out which should look pretty swish :)

**Comment by hyanwong** [comment] 2019-11-11 22:20
I'm not quite sure what you mean here. I didn't think that "display: none" was hardcoded anywhere into the homepage animation or tours module (but I could be wrong). Could you point to a line number?

**Comment by lentinj** [comment] 2019-11-12 09:45
``hide_and_show_stops()`` uses jQuery's ``.hide()`` and ``.show()``, which uses ``display: none``, which you can't animate.

Using something like ``.css({'opacity': 0})`` or an equivalent UI-kit class would allow the opacity to be animated, and CSS animations can fade that.

**Comment by hyanwong** [comment] 2019-11-12 12:38
Ah, ISWYM. I don't want to tie in the tours to using UIkit, or indeed any particular css stuff. It's also useful to be able to check `.is(":hidden")`. I guess the generic way to do this would be to provide an (overridable) setting option, so that we have e.g. a default of

```
"tourstop_shared": {
    "hide_tourstop_style":{"display":"none"},
    "show_tourstop_style":{"display":"block"},
    ...
}
```

And we can probably check for that style somehow, e.g. 

```
let shown_styles = settings.show_tourstop_style
if (shown_styles.keys().every((property) => {
    return(keep_shown.css(property) == shown_styles[property])})`
```

then in homepage_animation.js we can change the styles to e.g. ` "hide_tourstop_style":{"opacity":"0"}, "show_tourstop_style":{"opacity":"100"},...`

Does that seem like a reasonable workaround?

**Comment by lentinj** [comment] 2019-11-12 18:58
I don't think this really needs to be switchable. Setting/getting opacity and display:none is equivalent (the difference would be is opacity:0 would leave a hole in the page layout, but since they're stacked on top of each other that's irrelevant here).

**Comment by hyanwong** [comment] 2019-11-12 22:05
I read this too late, and had already coded it up as switchable, in https://github.com/OneZoom/OZtree/pull/221 - see if that works for you...

**Comment by jrosindell** [comment] 2019-12-04 15:03
Based on a review of the page here's what we think is outstanding...

- [ ] The animated tree does not pause when the window is backgrounded (possible waste of energy)
- [ ] Resizing the page (increasing size) messes up the tree leaving a white border on the right hadn't side
- [ ] Add fade in / out as discussed above is a good idea

**Comment by lentinj** [comment] 2019-12-09 11:08
@hyanwong Fading the whole thing in/out with opacity resulted in the tour controls blinking (there'd be a transition point between the two where they were both faded). Instead, I've added some stuff above to TourStop to add/remove classes, and then can do the right thing based on that.

**Comment by hyanwong** [comment] 2019-12-10 10:09
@lentinj OK, that sounds the most general solution - I prefer that anyway. Thanks.

**Comment by lentinj** [comment] 2019-12-10 16:38
> The animated tree does not pause when the window is backgrounded (possible waste of energy)

Had a brief play with this, it does initially look like it's stopped, but I think it's just that requestAnimationFrame gets throttled when the tab isn't visible, so it's really slow.

Instead, the above changes ``wait_and_goto_next()`` to check if the tree canvas is visible, if it's not keep waiting. This won't stop the tree mid-flight, but that's not the end of the world.

It should also stop if the page is scrolled beyond the canvas, I'll have a look at that next.

This probably won't be fool-proof, e.g. my browser doesn't know when the I'm on another virtual workspace, but we can't do much about that I think.

**Comment by hyanwong** [comment] 2019-12-10 19:00
> Instead, the above changes `wait_and_goto_next()` to check if the tree canvas is visible, if it's not keep waiting.

That's a nice, simple workaround. I agree with this. Thanks.

**Comment by lentinj** [comment] 2019-12-11 10:20
Listening for [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) instead of polling would be neater, but fiddly---I think the thing to do would be to first make an API that hooks DOM events, then a function call that returns a promise that is either resolved if visible, or resolves when it becomes visible. Then wait_and_goto_next could wait for it's timer and the visible promise, then carry on.

Problem with this would be is you won't be able to use the timer ID to cancel the goto_next, so this would need re-arranging.

And even if we did get rid of it, the tree itself will still be polling, so gains would be minimal.

**Comment by hyanwong** [comment] 2019-12-11 11:01
I don't think it needs to be too elegant. We just want to not drain batteries on mobile devices. It shouldn't matter whether the animation behaviour itself is super-consistent.

**Comment by lentinj** [comment] 2019-12-11 11:06
I'm not talking about the animation, with the above the wait_and_goto_next() timer is repeatedly popping up in the background asking the browser if it's visible yet. It's ~nil energy usage in comparison to doing the animations, but it's still waking up the browser's javascript engine and would be avoided in an ideal world.

**Comment by hyanwong** [comment] 2019-12-11 11:11
Oh yes, I see. I agree with your instinctive aversion to polling. Probably to be solved at the same time as stopping the tree polling, somehow.

**Comment by jrosindell** [comment] 2019-12-18 20:06
This is basically done now, but there are a few remaining issues.

- [ ] bug at start of the tour - first stop slow, it basically moves to the start of the tree when it's already there
- [ ] the icons need to be switched out for pause, stop, forward, back
- [ ]  the behaviour of the back button is not as expected - it doesn't always go back in the demo tour

**Comment by lentinj** [comment] 2019-12-18 21:20
> bug at start of the tour - first stop slow, it basically moves to the start of the tree when it's already there

Yes, I've seen this too, and sometimes there can even be a shuffle-backwards before the zoom starts. I'm fairly sure I know what's happening here. The flight code takes a start and end OZid, and if there isn't a start it goes for the biggest node on-screen (i.e. where you are). But on start-up there's race conditions here---or at least where it thinks you already are isn't quite right.

I'm not sure of any easy solutions off the top of my head though.

**Comment by jrosindell** [comment] 2020-03-28 11:44
In order to be easier on the eyes for people with seasickness the tree on the front page should zoom a lot faster and then pause for a fair while without any moving.

**Comment by jrosindell** [comment] 2020-03-28 12:11
Closing as now referenced in other smaller issues

**Closed by jrosindell** 2020-03-28 12:11 UTC
Labels: Homepage redesign
